package de.php_perfect.intellij.ddev.expose;

import org.jetbrains.annotations.NotNull;

/**
 * Generates the launchers that run an exposed command inside the web container.
 *
 * <p>Every launcher refuses to start a stopped project (which {@code ddev exec} would do on its
 * own), runs the command in the container directory matching the current one, rewrites project
 * paths in arguments to container paths, copies files outside the project into it so the
 * container can read them (and back afterwards), and rewrites container paths in the output to
 * host paths when the output is not a terminal, so tools reading it can resolve the files.</p>
 */
final class LauncherScripts {
    static final @NotNull String POWERSHELL_LAUNCHER = "ddev-exposed.ps1";

    private static final @NotNull String BASH = """
            #!/usr/bin/env bash
            # Generated by the DDEV Integration plugin and rewritten whenever a terminal opens.
            # Runs @COMMAND_COMMENT@ in the web container of the DDEV project @PROJECT_COMMENT@.
            # Compatible with the bash 3.2 that macOS ships.
            project=@PROJECT@
            approot=@APPROOT@
            ddev=@DDEV@
            command=@COMMAND@
            container_root=/var/www/html

            current=$PWD
            approot_windows=""
            case "$OSTYPE" in
              msys*|cygwin*)
                current=$(pwd -W)
                approot_windows=${approot//\\//\\\\}
                ;;
            esac

            if [ -n "$project" ] && command -v docker >/dev/null 2>&1 \\
                && names=$(docker ps --filter status=running --format '{{.Names}}' 2>/dev/null) \\
                && ! printf '%s\\n' "$names" | grep -qx "ddev-${project}-web"; then
              echo "The DDEV project ${project} is not running. Start it with: ddev start" >&2
              exit 1
            fi

            to_container() {
              local path=$1
              if [ -n "$approot_windows" ]; then
                case "$path" in
                  "$approot_windows"|"$approot_windows"\\\\*) path=${path//\\\\//} ;;
                esac
              fi
              case "$path" in
                "$approot") printf '%s' "$container_root" ;;
                "$approot"/*) printf '%s' "$container_root${path#"$approot"}" ;;
                *) return 1 ;;
              esac
            }

            translate_output() {
              local line
              local container_json='\\/var\\/www\\/html'
              local approot_json=${approot//\\//\\\\/}
              while IFS= read -r line || [ -n "$line" ]; do
                line=${line%$'\\r'}
                line=${line//"$container_root"/"$approot"}
                line=${line//"$container_json"/"$approot_json"}
                printf '%s\\n' "$line"
              done
            }

            dir=$(to_container "$current") || dir=$container_root

            tmpdir=""
            copies=()
            args=()
            for arg in "$@"; do
              if container_path=$(to_container "$arg"); then
                args+=("$container_path")
                continue
              fi
              case "$arg" in
                /*|[A-Za-z]:[\\\\/]*)
                  if [ -f "$arg" ]; then
                    if [ -z "$tmpdir" ]; then
                      tmpdir=$(mktemp -d "$approot/.ddev/.exposed-XXXXXX") || exit 1
                    fi
                    copy="$tmpdir/${#copies[@]}-${arg##*[\\\\/]}"
                    cp -p "$arg" "$copy" || exit 1
                    copies+=("$copy" "$arg")
                    args+=("$(to_container "$copy")")
                    continue
                  fi
                  ;;
              esac
              # An assignment, not a quoted expansion: bash 3.2 keeps quotes inside "${...//.../"..."}" literally.
              arg=${arg//"$approot"/"$container_root"}
              args+=("$arg")
            done

            restore() {
              local i
              for ((i = 0; i < ${#copies[@]}; i += 2)); do
                cmp -s "${copies[i]}" "${copies[i+1]}" || cp -p "${copies[i]}" "${copies[i+1]}"
              done
              if [ -n "$tmpdir" ]; then
                rm -rf "$tmpdir"
              fi
            }

            cd "$approot" || exit 1
            if [ -t 1 ]; then
              "$ddev" exec@QUIET@ --raw --dir "$dir" -- "$command" "${args[@]}"
              status=$?
            else
              "$ddev" exec@QUIET@ --raw --dir "$dir" -- "$command" "${args[@]}" | translate_output
              status=${PIPESTATUS[0]}
            fi
            restore
            exit "$status"
            """;

    private static final @NotNull String POWERSHELL = """
            # Generated by the DDEV Integration plugin and rewritten whenever a terminal opens.
            # Runs a command in the web container of the DDEV project @PROJECT_COMMENT@.
            # There is no param block, so arguments such as -a reach the command instead of binding to parameters.
            $project = @PROJECT@
            $approot = @APPROOT@
            $ddev = @DDEV@
            $containerRoot = '/var/www/html'
            $command = $args[0]
            $arguments = @($args | Select-Object -Skip 1)

            if ($project -and (Get-Command docker -ErrorAction SilentlyContinue)) {
                $names = & docker ps --filter status=running --format '{{.Names}}' 2>$null
                if ($LASTEXITCODE -eq 0 -and @($names) -notcontains "ddev-$project-web") {
                    [Console]::Error.WriteLine("The DDEV project $project is not running. Start it with: ddev start")
                    exit 1
                }
            }

            function ConvertTo-ContainerPath([string] $Path) {
                $normalized = $Path.Replace('/', '\\')
                if ($normalized.Equals($approot, [StringComparison]::OrdinalIgnoreCase)) {
                    return $containerRoot
                }
                if ($normalized.StartsWith($approot + '\\', [StringComparison]::OrdinalIgnoreCase)) {
                    return $containerRoot + $normalized.Substring($approot.Length).Replace('\\', '/')
                }
                return $null
            }

            $approotJson = $approot.Replace('\\', '\\\\')
            function Convert-Line([string] $Line) {
                $Line = [regex]::Replace($Line, '/var/www/html((?:/[^\\s:"'']*)?)', {
                    param($match) $approot + $match.Groups[1].Value.Replace('/', '\\')
                })
                return $Line.Replace('\\/var\\/www\\/html', $approotJson)
            }

            $dir = ConvertTo-ContainerPath (Get-Location).ProviderPath
            if (-not $dir) {
                $dir = $containerRoot
            }

            $tmp = $null
            $copies = @()
            $translated = @()
            foreach ($argument in $arguments) {
                $containerPath = ConvertTo-ContainerPath $argument
                if ($containerPath) {
                    $translated += $containerPath
                    continue
                }
                if ([IO.Path]::IsPathRooted($argument) -and (Test-Path -LiteralPath $argument -PathType Leaf)) {
                    if (-not $tmp) {
                        $tmp = Join-Path $approot ('.ddev\\.exposed-' + [Guid]::NewGuid().ToString('N'))
                        New-Item -ItemType Directory -Path $tmp | Out-Null
                    }
                    $copy = Join-Path $tmp ("$($copies.Count)-" + [IO.Path]::GetFileName($argument))
                    Copy-Item -LiteralPath $argument -Destination $copy
                    $copies += ,@($copy, $argument)
                    $translated += ConvertTo-ContainerPath $copy
                    continue
                }
                $translated += $argument
            }

            # A quoted '--' reaches ddev; a bare one would end PowerShell's own parameter parsing.
            $execArguments = @('exec'@QUIET_PS@, '--raw', '--dir', $dir, '--', $command) + $translated
            Push-Location -LiteralPath $approot
            try {
                if ([Console]::IsOutputRedirected) {
                    & $ddev @execArguments | ForEach-Object { Convert-Line $_ }
                } else {
                    & $ddev @execArguments
                }
                $status = $LASTEXITCODE
            } finally {
                Pop-Location
                foreach ($pair in $copies) {
                    if ((Get-FileHash -LiteralPath $pair[0]).Hash -ne (Get-FileHash -LiteralPath $pair[1]).Hash) {
                        Copy-Item -LiteralPath $pair[0] -Destination $pair[1] -Force
                    }
                }
                if ($tmp) {
                    Remove-Item -LiteralPath $tmp -Recurse -Force
                }
            }
            exit $status
            """;

    private LauncherScripts() {
    }

    /**
     * @param approot     the project root as the shell sees it: a POSIX path, or {@code C:/...} for Git Bash
     * @param quietFlag   whether {@code ddev exec --quiet} is available (DDEV 1.24.7 and later)
     */
    static @NotNull String bash(@NotNull String projectName, @NotNull String approot, @NotNull String ddevBinary,
                                @NotNull String command, boolean quietFlag) {
        return BASH
                .replace("@COMMAND_COMMENT@", comment(command))
                .replace("@PROJECT_COMMENT@", comment(projectName))
                .replace("@PROJECT@", shellQuote(projectName))
                .replace("@APPROOT@", shellQuote(approot))
                .replace("@DDEV@", shellQuote(ddevBinary))
                .replace("@COMMAND@", shellQuote(command))
                .replace("@QUIET@", quietFlag ? " --quiet" : "");
    }

    /**
     * @param approot the project root as a Windows path, e.g. {@code C:\Users\me\site}
     */
    static @NotNull String powershell(@NotNull String projectName, @NotNull String approot, @NotNull String ddevBinary,
                                      boolean quietFlag) {
        return POWERSHELL
                .replace("@PROJECT_COMMENT@", comment(projectName))
                .replace("@PROJECT@", powershellQuote(projectName))
                .replace("@APPROOT@", powershellQuote(approot))
                .replace("@DDEV@", powershellQuote(ddevBinary))
                .replace("@QUIET_PS@", quietFlag ? ", '--quiet'" : "")
                .replace("\n", "\r\n");
    }

    /**
     * The {@code .cmd} file that makes {@code command} callable from cmd and PowerShell.
     */
    static @NotNull String cmd(@NotNull String command) {
        return "@echo off\r\n"
                + "powershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -File \"%~dp0" + POWERSHELL_LAUNCHER + "\" "
                + command + " %*\r\n"
                + "exit /b %ERRORLEVEL%\r\n";
    }

    private static @NotNull String shellQuote(@NotNull String value) {
        return "'" + value.replace("'", "'\\''") + "'";
    }

    private static @NotNull String powershellQuote(@NotNull String value) {
        return "'" + value.replace("'", "''") + "'";
    }

    private static @NotNull String comment(@NotNull String value) {
        return value.replaceAll("[\\r\\n]", " ");
    }
}
