name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v5

      # Validate wrapper
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v4

      # Set up Java environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Build project
        run: ./gradlew buildPlugin --exclude-task test

      - name: Upload Assets
        uses: actions/upload-artifact@v4
        with:
          name: ddev-intellij-plugin
          path: build/distributions/*.zip
