name: New Issue

on:
  issues:
    types: [ opened ]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v4
        with:
          project-name: Development
          column-name: New
