name: Publish Release

on:
  release:
    types: [prereleased, released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Extract Tag Name
        uses: olegtarasov/get-tag@v2.1

      # Validate wrapper
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.1.0

      # Set up Java environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Extract Channel from Version
        uses: actions-ecosystem/action-regex-match@v2
        id: match-channel
        with:
          text: ${{ github.ref }}
          regex: '(eap|beta|alpha)\d*$'

      - name: Publish to JetBrains Marketplace
        uses: gradle/gradle-build-action@v3
        with:
          arguments: publishPlugin
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
        env:
          CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
          JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_TOKEN }}
          PUBLISH_CHANNEL: ${{ steps.match-channel.outputs.group1 }}

      - name: Update GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: build/distributions/*.zip

  sentry_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Tag Name
        uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          version: ${{ steps.tagName.outputs.tag }}
