name: Publish Release

on:
  push:
    branches: [ main ]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-eap*'
      - '[0-9]+.[0-9]+.[0-9]+-beta*'
      - '[0-9]+.[0-9]+.[0-9]+-alpha*'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract Tag Name
        uses: olegtarasov/get-tag@v2.1

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin

      - name: Run Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract Tag Name
        uses: olegtarasov/get-tag@v2.1

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin

      - name: Verify Plugin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: runPluginVerifier
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

  release:
    needs: [ tests, verify ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract Tag Name
        uses: olegtarasov/get-tag@v2.1

      - name: Make Gradlew Executable
        run: chmod +x gradlew

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: buildPlugin --exclude-task test
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ddev-intellij-plugin
          path: build/distributions/*.zip

      - name: Extract Changelog
        id: gradle-changelog
        run: ./gradlew getChangelog --quiet --no-header --console=plain > build/extracted_release_changelog.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ contains(github.ref, 'eap') || contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
          fail_on_unmatched_files: true
          files: build/distributions/*.zip
          body_path: build/extracted_release_changelog.md

  publish:
    needs: [ release ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract Tag Name
        uses: olegtarasov/get-tag@v2.1

      - name: Make Gradlew Executable
        run: chmod +x gradlew

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Extract Channel from Version
        uses: actions-ecosystem/action-regex-match@v2
        id: match-channel
        with:
          text: ${{ github.ref }}
          regex: '(eap|beta|alpha)\d*$'

      - name: Publish Release
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishPlugin
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
        env:
          CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
          JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_TOKEN }}
          PUBLISH_CHANNEL: ${{ steps.match-channel.outputs.group1 }}
