name: Create Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-eap.*'
      - '[0-9]+.[0-9]+.[0-9]+-beta.*'
      - '[0-9]+.[0-9]+.[0-9]+-alpha.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Extract Tag Name
        uses: olegtarasov/get-tag@v2.1
        id: tagName

      # Validate wrapper
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v2.0.0

      # Set up Java environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Extract Changelog
        id: gradle-changelog
        run: ./gradlew getChangelog --quiet --no-header --console=plain > build/extracted_release_changelog.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ contains(github.ref, 'eap') || contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
          body_path: build/extracted_release_changelog.md
