name: Publish Release

on:
  push:
#    branches: [ main ]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-eap*'
      - '[0-9]+.[0-9]+.[0-9]+-beta*'
      - '[0-9]+.[0-9]+.[0-9]+-alpha*'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin

      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

  release:
    needs: [ tests ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: buildPlugin --exclude-task test

      - name: Upload jar file
        uses: actions/upload-artifact@v2
        with:
          name: ddev-intellij-plugin
          path: build/distributions/*.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: ${{ contains(github.ref, 'eap') || contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
          fail_on_unmatched_files: true
          files: build/distributions/*.zip

  publish:
    needs: [ release ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Make Gradlew Executable
        run: chmod +x gradlew

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Extract Channel from Version
        uses: actions-ecosystem/action-regex-match@v2
        id: match-channel
        with:
          text: ${{ github.ref }}
          regex: '(eap|beta|alpha)\d*$'

#      - name: Publish Release
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: publishPlugin
#        env:
#          CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
#          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
#          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
#          JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_TOKEN }}
#          PUBLISH_CHANNEL: ${{ steps.match-channel.outputs.group1 }}
