name: Verify Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Extract Tag Name
        uses: olegtarasov/get-tag@v2.1

      # Validate wrapper
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.1.0

      # Set up Java environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Verify Plugin
        uses: gradle/gradle-build-action@v3
        with:
          arguments: runPluginVerifier --stacktrace --info
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report-${{ matrix.os }}
          path: build/reports/pluginVerifier/*/report.html
          if-no-files-found: error
