package de.php_perfect.intellij.ddev.actions;

import com.intellij.openapi.application.ApplicationManager;
import com.intellij.openapi.fileEditor.FileEditorManager;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.Messages;
import com.intellij.openapi.vfs.LocalFileSystem;
import com.intellij.openapi.vfs.VirtualFile;
import de.php_perfect.intellij.ddev.DdevIntegrationBundle;
import de.php_perfect.intellij.ddev.state.DdevStateManager;
import de.php_perfect.intellij.ddev.state.State;
import org.jetbrains.annotations.NotNull;

import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Opens the webserver configuration generated by DDEV
 * ({@code .ddev/nginx_full/nginx-site.conf} or {@code .ddev/apache/apache-site.conf}).
 */
public final class DdevEditWebserverConfigAction extends DdevRunAction {
    @Override
    protected void run(@NotNull Project project) {
        final String basePath = project.getBasePath();

        if (basePath == null) {
            return;
        }

        final Path nginxConf = Path.of(basePath, ".ddev", "nginx_full", "nginx-site.conf");
        final Path apacheConf = Path.of(basePath, ".ddev", "apache", "apache-site.conf");
        final Path config = Files.exists(nginxConf) ? nginxConf : (Files.exists(apacheConf) ? apacheConf : null);

        if (config == null) {
            Messages.showInfoMessage(project,
                    DdevIntegrationBundle.message("editWebserverConfig.missing.message"),
                    DdevIntegrationBundle.message("editWebserverConfig.missing.title"));
            return;
        }

        ApplicationManager.getApplication().invokeLater(() -> {
            final VirtualFile virtualFile = LocalFileSystem.getInstance().refreshAndFindFileByNioFile(config);

            if (virtualFile != null) {
                FileEditorManager.getInstance(project).openFile(virtualFile, true);
            }
        });
    }

    @Override
    protected boolean isActive(@NotNull Project project) {
        final State state = DdevStateManager.getInstance(project).getState();

        return state.isAvailable() && state.isConfigured();
    }
}
